name: Trigger ROM Build

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook Request
        run: |
          curl -A "Tomodachi Build" -X POST ${{ secrets.API_URL }} \
               -H "X-Webhook-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
               -H "Content-Type: application/json" \
               -d '{"action": "build_rom"}'
